import type { Metadata } from "next";
import "./globals.css";
import { NextIntlClientProvider } from "next-intl";
import Box from "@mui/material/Box";
import { Navbar } from "../components/layout/navbar";
import Footer from "../components/layout/footer/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <NextIntlClientProvider>
          <Box
            minHeight={"100vh"}
            display={"flex"}
            flexDirection={"column"}
          >
            <Navbar />
            <Box component="main" flex="1">
              {children}
            </Box>
            <Footer />
          </Box>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
